### ISSUE TITLE
CSS headings overlapping upward links

### ISSUE THREAD

**Issue by honzagrec** [apifytech/apify-docs#64]
Seems CSS gives all h2, h3, h4 and maybe more (but haven't crossed any) headings `padding-top: 80px;` property, which seems to cause overlapping of links in the end of previous paragraph making them non-clickable.

Examples:  
https://docs.apify.com/scraping#web-scraper link `Visit the Scraper introduction tutorial to get started!`  
https://docs.apify.com/scraping/getting-started#webhooks link `which you can find under your plan`

**Comment by vbartonicek** [comment]
Hi Honza, thank you for reporting this bug! We already fixed that ;-) Let us know if there is anything we can improve ;-)
